a = input('Digite algo:')
print('O tipo primitivo desse valor é:',(type(a)))
print('Só tem espaços?',(a.isspace()))
print('É um númerico:',(a.isnumeric()))
print('É alfabético:',(a.isalpha()))
print('É alfanumerico:',(a.isalnum()))
print('Está em maiúsculas?:',(a.istitle()))
print('Está em minúsculas?',(a.isalpha()))
print('Está capitalizada?',(a.isalpha()))